echo "------------------------------------"
echo "This file contains the SMS variables"
echo "------------------------------------"
#
export SMSNAME=%SMSNAME%
export SMSWORK=%SMSWORK%
export SMSGIF=%SMSGIF%
export SMSOUT=%SMSOUT%
export EXPVER="%EXPVER%"
export TYPFOR="%TYPFOR%"
export CLASS="%CLASS%"
export STREAM="%STREAM%"
export METHOD="%METHOD%"
export SYSTEM="%SYSTEM%"
export ORIGIN="%ORIGIN%"
export NENS="%NENS%"
export ANIN=%ANIN%
export MULTI=%MULTI%
export YY1=%START_YEAR%
export MM1="%START_MONTH%"
export DD1="%START_DAY%"
export TT1="%START_TIME%"
export YY2=%END_YEAR%
export NMON=%FCLENMON%
export CROS=%CROS%
export PLST="%PLST%"
export LLST="%LLST%"
export TLST="%TLST%"
export FLST="%FLST%"
export MLST="%MLST%"
export SET_228=%SET_228%
export YY1_228=%YY1_228%
export SDIA="%SDIA%"
export EDIA="%EDIA%"
export RDIA="%RDIA%"
export ECDISK=%ECDISK%
export ECSTORE=%ECSTORE%
export DISP=%DISP%
export FORCEBIAS=%FORCEBIAS%
export BIAS_ECST=%BIAS_ECST%
export BIAS_GIF=%BIAS_GIF%
export FORCEANRE=%FORCEANRE%
export FORCEANMO=%FORCEANMO%
export FORCEPDFC=%FORCEPDFC%
export PDF_TYP=%PDF_TYP%
export PDF_PER=%PDF_PER%
export PDF_SIG=%PDF_SIG%
export PDF_ECST=%PDF_ECST%
export FORCETRD=%FORCETRD%
export TRD_ECST=%TRD_ECST%
export ACC_MAP="%ACCMAP%"
export FORCEACC=%FORCEACC%
export ACC_BOOT=%ACC_BOOT%
export ACC_NSAM=%ACC_NSAM%
export ACC_TOPTH=%ACC_TOPTH%
export ACC_BOTTH=%ACC_BOTTH%
export ACSP_ECST=%ACSP_ECST%
export ACSP_GIF=%ACSP_GIF%
export TSDIA="%TSDIA%"
export FORCETS=%FORCETS%
export TS_GIF=%TS_GIF%
export TS_ECST=%TS_ECST%
export FORCEBRV="%FORCEBRV%"
export BRV_MAP="%BRVMAP%"
export BRV_EVT="%BRV_EVT%"
export BRV_PERM=%BRV_PERM%
export BRV_IPRB=%BRV_IPRB%
export BRV_NPRO=%BRV_NPRO%
export BRV_BOOT=%BRV_BOOT%
export BRV_NSAM=%BRV_NSAM%
export BRV_TOPTH=%BRV_TOPTH%
export BRV_BOTTH=%BRV_BOTTH%
export BRV_ECST=%BRV_ECST%
export BRV_GIF=%BRV_GIF%
#
echo "-----------------------------"
echo "This is the end of sms_vars.h"
echo "-----------------------------"
